"""add_auth_columns_to_users

Revision ID: 9da75d215e3a
Revises: 7611f2057b39
Create Date: 2025-09-08 13:41:31.773499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9da75d215e3a"
down_revision: Union[str, Sequence[str], None] = "7611f2057b39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("roles", sa.ARRAY(sa.String()), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
